//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteSushi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Detail
    {
        public int id_menu_detail { get; set; }
        public string name_food_detail { get; set; }
        public Nullable<int> price_food_detail { get; set; }
        public Nullable<int> id_menu { get; set; }
        public string image_food_detail { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
